### ISSUE TITLE
bug on argments

### ISSUE THREAD

**Issue by DiscoveringWorld** [fre3d0m1/bot-detector#34]
botdetector a a
- Initializing.. -
Traceback (most recent call last):
  File "C:\Users\decou\AppData\Local\Programs\Python\Python39\Scripts\botdetector-script.py", line 33, in <module>
    sys.exit(load_entry_point('bot-detector==0.2.5', 'console_scripts', 'botdetector')())
  File "C:\Users\decou\AppData\Local\Programs\Python\Python39\lib\site-packages\botdetector\__main__.py", line 17, in main
    if arguments_reader.read_args(args[0], args[1:]) == False:
  File "C:\Users\decou\AppData\Local\Programs\Python\Python39\lib\site-packages\botdetector\ArgumentsReader.py", line 61, in read_args
    if len(args) < minimum_lengths[command_type]:
KeyError: 'a'

**Comment by fre3d0m1** [comment]
We're on it now!

**Comment by fre3d0m1** [comment]
It should now be fixed in v0.2.6.
