### ISSUE TITLE
should detect if a connection to internet is available before 

### ISSUE THREAD

**Issue by DiscoveringWorld** [fre3d0m1/bot-detector#38]
botdetector run test followers
- Initializing.. -
Traceback (most recent call last):
  File "C:\Users\decou\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\decou\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\decou\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by fre3d0m1** [comment]
Try updating the program on your machine and then running the command again.

**Comment by DiscoveringWorld** [comment]
good it's check well now.
